run:
  timeout: 5m
  skip-files:
    - "zz_generated_*"
  tests: false
output:
  format: github-actions
linters:
  enable:
    - revive # replacement for golint
    - dupl # check duplicated code
    - goconst # check strings that can turn into constants
    - gofmt # check fmt
    - goimports # check imports
linters-settings:
  revive:
    rules:
      # The following rules are recommended https://github.com/mgechev/revive#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
issues:
  exclude-rules:
  - linters:
    - revive
    text: "var-naming: don't use an underscore in package name"
    path: 'mock(\w+)/doc.go$'
